server:
  port : 9998

spring:
  jmx:
    enabled: false
  cloud:
    gateway:
      routes:
        - id: bns-kr
          uri: http://local.com:9999
          predicates:
            - Path=/local/v1.0/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
